name: Development Workflow # Ensure code is working before previewing deployment

on: 
  pull_request:
    branches:
      - dev # Trigger when a pull request is merged into the Dev branch
    types:
      - closed  # Only trigger when the PR is closed (merged)
  push:
    branches:
      - dev # Trigger on direct push to Dev

  workflow_dispatch:

jobs:
  merge-to-staging:
    environment: Staging
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Staging branch
      uses: actions/checkout@v4
      with:
        ref: staging  # Explicitly checkout the staging branch

    - name: Fetch the Dev branch
      run: git fetch origin dev  # Fetch the Dev branch

    - name: Merge Dev into Staging
      run: git merge origin/dev --allow-unrelated-histories -m "Merge from Dev to Staging"

    - name: Push code to Staging
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

